"""add_sessao_id_to_chat_messages

Revision ID: 1046109fa1a2
Revises: b034186cbf34
Create Date: 2026-06-07 16:39:09.283749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1046109fa1a2'
down_revision: Union[str, None] = 'b034186cbf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adiciona como nullable para não falhar em linhas existentes
    op.add_column('chat_messages', sa.Column('sessao_id', sa.Uuid(), nullable=True))
    # Preenche linhas existentes com um UUID fixo (serão de sessões legadas)
    op.execute("UPDATE chat_messages SET sessao_id = gen_random_uuid() WHERE sessao_id IS NULL")
    # Agora torna NOT NULL
    op.alter_column('chat_messages', 'sessao_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'sessao_id')
    # ### end Alembic commands ###
