"""initial schema

Revision ID: abdb546095c0
Revises: 
Create Date: 2026-05-28 15:03:38.659781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'abdb546095c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativas_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limite', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('dia_fechamento', sa.Integer(), nullable=True),
    sa.Column('mes_offset_vencimento', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartoes_usuario_id'), 'cartoes', ['usuario_id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_usuario_id'), 'categorias', ['usuario_id'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forma_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_gasto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=True),
    sa.Column('fatura_mes', sa.Integer(), nullable=True),
    sa.Column('fatura_ano', sa.Integer(), nullable=True),
    sa.Column('parcelado', sa.Boolean(), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_usuario_id'), 'transacoes', ['usuario_id'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('taxa_juros', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_juros', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.Column('fatura_mes', sa.Integer(), nullable=True),
    sa.Column('fatura_ano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelas_transacao_id'), 'parcelas', ['transacao_id'], unique=False)
    op.create_index(op.f('ix_parcelas_usuario_id'), 'parcelas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcelas_usuario_id'), table_name='parcelas')
    op.drop_index(op.f('ix_parcelas_transacao_id'), table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index(op.f('ix_transacoes_usuario_id'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index(op.f('ix_categorias_usuario_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_cartoes_usuario_id'), table_name='cartoes')
    op.drop_table('cartoes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
