#!/usr/bin/env python3
"""
travar_deps.py — gera (e confere) o LOCK de dependências do hivvo-api.

Por que existe: até o T-XX o requirements.txt especificava tudo com `>=` e não
havia lock. Cada instalação limpa resolvia o que fosse mais novo NAQUELE
MOMENTO, então local, CI e Railway rodavam conjuntos diferentes sem ninguém
decidir isso. Foi assim que a suíte ficou verde na máquina do dev contra
fastapi 0.136.3 enquanto produção já rodava 0.141.1 — versão em que
`include_router` deixou de achatar as sub-rotas em `app.routes` e um teste de
topologia caiu só no CI.

Fonte da verdade agora:
  requirements.in      → intenções de produção (editar À MÃO)
  requirements-dev.in  → intenções de dev/teste (editar À MÃO)
  requirements.txt     → GERADO, travado em ==, com as transitivas
  requirements-dev.txt → GERADO, idem (já contém as de produção)

O requirements.txt continua sendo o arquivo que a Railway instala no build, no
mesmo caminho de sempre: travar não mudou o contrato com a plataforma.

Uso:
    python scripts/travar_deps.py            # regenera os dois .txt
    python scripts/travar_deps.py --check    # não escreve; sai 1 se houver desvio

O --check é o que o CI roda antes do pip install. Sem ele nada impediria editar
o arquivo gerado à mão ou mudar o .in sem recompilar, e o lock viraria
documentação — que é o estado de que este script nos tirou.
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent

# Fixada de propósito: versões diferentes do uv podem formatar a saída de outro
# jeito, e o --check compara o TEXTO INTEIRO — qualquer diferença de formatação
# vira desvio. Ao subir esta versão, regenere os dois .txt no mesmo commit e
# alinhe o pin do ci.yml.
UV_VERSAO = "0.12.5"

# --universal: um único lock serve Windows (dev) e Linux (CI/Railway). A
# resolução por plataforma vira marcador de ambiente na própria linha, em vez de
# um arquivo por sistema operacional — e é o que permite o CI (Ubuntu) recompilar
# e comparar com o que foi gerado aqui.
# --python-version: a mesma do ci.yml. Ao mudar uma, mude a outra.
PYTHON_ALVO = "3.13"

# --exclude-newer: CORTA o índice nesta data. É o que torna a recompilação
# determinística, e não é conveniência — é o que faz o --check valer alguma
# coisa. Sem ele, a única forma de recompilar sem falhar por calendário seria
# deixar o uv ler o próprio arquivo de saída como PREFERÊNCIA; e aí um pin
# rebaixado à mão (tzdata==2026.2, digamos, que ainda satisfaz o >=2024.1 do
# .in) seria RESPEITADO pela recompilação e o desvio passaria batido. Medi
# antes de escolher: passava mesmo. Com o corte no tempo, a resolução não
# depende do que está no arquivo, então edição à mão reaparece como diferença.
#
# ATUALIZAR DEPENDÊNCIAS = subir esta data e rodar o script. É deliberado: a
# data é a decisão de "aceito o que foi publicado até aqui", ela aparece no
# diff do PR, e alguém aprova. Enquanto ela não subir, nenhum release novo
# entra sozinho — nem no CI, nem no build da Railway.
EXCLUDE_NEWER = "2026-08-23T23:59:59Z"

PARES = [
    ("requirements.in", "requirements.txt"),
    ("requirements-dev.in", "requirements-dev.txt"),
]


def _cabecalho(entrada: str, saida: str) -> str:
    """Texto do cabeçalho do arquivo gerado.

    A primeira linha é o comando de regeneração (o uv a imprime logo abaixo do
    "autogenerated by uv via the following command"). As demais são o aviso.
    """
    return (
        f"python scripts/travar_deps.py\n"
        f"#\n"
        f"# ============================================================\n"
        f"#  ARQUIVO GERADO — NÃO EDITE À MÃO.\n"
        f"# ============================================================\n"
        f"# Para mudar uma dependência, edite {entrada} e rode:\n"
        f"#\n"
        f"#     python scripts/travar_deps.py\n"
        f"#\n"
        f"# Por baixo, o comando exato é:\n"
        f"#\n"
        f"#     uv pip compile {entrada} --universal\n"
        f"#         --python-version {PYTHON_ALVO}\n"
        f"#         --exclude-newer {EXCLUDE_NEWER}\n"
        f"#         --output-file {saida}\n"
        f"#\n"
        f"# Gerado com uv {UV_VERSAO}. O CI recompila a partir do .in e FALHA se o\n"
        f"# resultado diferir deste arquivo, então editar aqui à mão não cola:\n"
        f"# a recompilação não lê os pins daqui, ela os RESOLVE de novo.\n"
        f"#\n"
        f"# PARA ATUALIZAR AS DEPENDÊNCIAS: suba EXCLUDE_NEWER em\n"
        f"# scripts/travar_deps.py e rode o script. Enquanto essa data não\n"
        f"# subir, nenhum release publicado depois dela entra — nem aqui, nem\n"
        f"# no build da Railway.\n"
        f"#\n"
        f"# Item futuro (fora do escopo do commit que travou): --generate-hashes,\n"
        f"# que fixa também o sha256 de cada wheel e fecha a janela de um release\n"
        f"# ser republicado com o mesmo número de versão."
    )


def _uv() -> list[str]:
    """Localiza o uv: executável no PATH, senão o módulo do interpretador atual."""
    caminho = shutil.which("uv")
    if caminho:
        return [caminho]
    return [sys.executable, "-m", "uv"]


def _compilar(entrada: str, saida: Path) -> None:
    comando = [
        *_uv(), "pip", "compile", str(RAIZ / entrada),
        "--universal",
        "--python-version", PYTHON_ALVO,
        "--exclude-newer", EXCLUDE_NEWER,
        "--custom-compile-command", _cabecalho(entrada, saida.name),
        "--output-file", str(saida),
        "--quiet",
    ]
    proc = subprocess.run(comando, cwd=RAIZ, text=True, encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        raise SystemExit(f"uv pip compile falhou em {entrada} (rc={proc.returncode})")


def gerar() -> int:
    for entrada, saida in PARES:
        _compilar(entrada, RAIZ / saida)
        print(f"  gerado: {saida}")
    return 0


def conferir() -> int:
    """Recompila num diretório temporário e compara com o que está commitado.

    Compila do ZERO, sem semear o destino com o arquivo commitado: o corte de
    EXCLUDE_NEWER já torna a resolução determinística, então não é preciso —
    nem desejável — deixar o uv usar os pins atuais como preferência. É por não
    usá-los que uma edição à mão no arquivo gerado aparece aqui como diferença.

    O QUE ESTA COMPARAÇÃO NÃO PEGA: fim de linha. O `read_text()` abaixo abre em
    modo texto com newline=None, ou seja, universal-newlines — CRLF e CR viram
    LF na leitura, dos DOIS lados, antes do `==`. Um requirements.txt commitado
    com CRLF confere com um recompilado em LF e o --check passa. Isso é
    proposital (o mesmo lock é lido no Windows e no Linux, e o fim de linha não
    é parte do que o lock promete), mas não confunda com verificação de bytes:
    quem garante o conteúdo byte a byte é o .gitattributes, não este portão.
    """
    desviados: list[str] = []

    with tempfile.TemporaryDirectory() as tmp:
        for entrada, saida in PARES:
            commitado = RAIZ / saida
            if not commitado.exists():
                print(f"  AUSENTE: {saida} não existe (rode sem --check)")
                desviados.append(saida)
                continue

            recompilado = Path(tmp) / saida
            _compilar(entrada, recompilado)

            atual = commitado.read_text(encoding="utf-8")
            novo = recompilado.read_text(encoding="utf-8")
            if atual == novo:
                print(f"  ok: {saida} confere com {entrada}")
                continue

            desviados.append(saida)
            print(f"\n  *** DESVIO em {saida} ***")
            import difflib

            diff = difflib.unified_diff(
                atual.splitlines(keepends=True),
                novo.splitlines(keepends=True),
                fromfile=f"{saida} (commitado)",
                tofile=f"{saida} (recompilado de {entrada})",
            )
            for linha in diff:
                print(f"  | {linha.rstrip()}")

    if desviados:
        print(
            "\nO lock está fora de sincronia com os .in: "
            + ", ".join(desviados)
            + "\nRode `python scripts/travar_deps.py` e commite o resultado."
        )
        return 1

    print("\nLock em dia — os .txt são exatamente o que os .in resolvem.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--check",
        action="store_true",
        help="não escreve nada; sai 1 se o lock commitado não bater com os .in",
    )
    args = parser.parse_args()
    return conferir() if args.check else gerar()


if __name__ == "__main__":
    raise SystemExit(main())
